sudo: false
env:
  global:
  - TRAVIS_NODE_VERSION="4.2"
matrix:
  include:
  - env: PLATFORM=ios-9.3
    os: osx
    osx_image:
      - xcode8
    language: node_js
    node_js: "4.2"
  - env: PLATFORM=ios-10.0
    os: osx
    osx_image:
      - xcode8
      - xcode9
      - xcode10
    language: node_js
    node_js: "4.2"
  - env: PLATFORM=android-4.4
    os: linux
    language: android
    jdk:
     - oraclejdk8
    android:
      components:
      - tools
      - extra-android-m2repository
      - build-tools-26.0.2
  - env: PLATFORM=android-5.1
    os: linux
    language: android
    jdk:
     - oraclejdk8
     - openjdk8
    android:
      components:
      - tools
      - extra-android-m2repository
      - build-tools-26.0.2
  - env: PLATFORM=android-6.0
    os: linux
    language: android
    jdk:
     - oraclejdk9
     - openjdk8
    android:
      components:
      - tools
      - extra-android-m2repository
      - build-tools-22.0.1
  - env: PLATFORM=android-7.0
    os: linux
    language: android
    jdk:
     - oraclejdk8
     - oraclejdk9
     - openjdk8
     - oraclejdk10
     - openjdk10
     - openjdk11
    android:
      components:
      - tools
      - extra-android-m2repository
      - build-tools-26.0.2

before_install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- node --version
- if [[ "$PLATFORM" =~ android ]]; then gradle --version; fi
- if [[ "$PLATFORM" =~ ios ]]; then npm install -g ios-deploy; fi
- if [[ "$PLATFORM" =~ android ]];
  then echo y | android update sdk -u --filter android-22,android-23,android-24,android-25,android-26,android-27;
  fi
- npm install -g cordova

install:
- npm install

script:
- make all
- ./test/run.sh cc.fovea.babygoo babygooinapp1
